import path from 'node:path';
import fs from 'node:fs/promises';
import ts from 'typescript';

interface ExportDoc {
  name: string;
  kind: 'function' | 'interface';
  signature?: string;
  declaration?: string;
  documentation?: string;
  tags?: string[];
}

interface FileDoc {
  filePath: string;
  exports: ExportDoc[];
}

async function ensureDirectory(filePath: string): Promise<void> {
  await fs.mkdir(path.dirname(filePath), { recursive: true });
}

function loadProgram(root: string): ts.Program {
  const configPath = path.join(root, 'tsconfig.deliverables.json');
  const configFile = ts.readConfigFile(configPath, ts.sys.readFile);
  if (configFile.error) {
    const message = ts.flattenDiagnosticMessageText(configFile.error.messageText, '\n');
    throw new Error(`Failed to read tsconfig.deliverables.json: ${message}`);
  }

  const parsed = ts.parseJsonConfigFileContent(configFile.config, ts.sys, root);
  const deliverablesRoot = path.join(root, 'electron', 'deliverables');
  const fileNames = parsed.fileNames.filter((file) => file.startsWith(deliverablesRoot) && file.endsWith('.ts'));

  return ts.createProgram(fileNames, parsed.options);
}

function formatDocumentation(symbol: ts.Symbol, checker: ts.TypeChecker): { text?: string; tags?: string[] } {
  const doc = ts.displayPartsToString(symbol.getDocumentationComment(checker)).trim();
  const tags = symbol.getJsDocTags().map((tag) => {
    const text = tag.text?.map((part) => part.text).join('') ?? '';
    return text ? `@${tag.name} ${text}`.trim() : `@${tag.name}`;
  });
  return { text: doc || undefined, tags: tags.length > 0 ? tags : undefined };
}

function collectExportDocs(program: ts.Program): FileDoc[] {
  const checker = program.getTypeChecker();
  const printer = ts.createPrinter({ newLine: ts.NewLineKind.LineFeed });
  const docs: FileDoc[] = [];

  for (const sourceFile of program.getSourceFiles()) {
    if (sourceFile.isDeclarationFile) {
      continue;
    }
    const fileName = sourceFile.fileName;
    if (!fileName.includes(`${path.sep}electron${path.sep}deliverables${path.sep}`)) {
      continue;
    }

    const moduleSymbol = checker.getSymbolAtLocation(sourceFile) ?? (sourceFile as unknown as { symbol?: ts.Symbol }).symbol;
    if (!moduleSymbol) {
      continue;
    }

    const exports = checker.getExportsOfModule(moduleSymbol);
    const exportDocs: ExportDoc[] = [];

    for (const symbol of exports) {
      if (symbol.name === 'default') {
        continue;
      }

      const declarations = symbol.getDeclarations()?.filter((decl) => decl.getSourceFile() === sourceFile) ?? [];
      if (declarations.length === 0) {
        continue;
      }

      const { text: documentation, tags } = formatDocumentation(symbol, checker);

      let recorded = false;

      for (const declaration of declarations) {
        if (ts.isInterfaceDeclaration(declaration)) {
          const printed = printer.printNode(ts.EmitHint.Unspecified, declaration, sourceFile).trim();
          exportDocs.push({
            name: symbol.getName(),
            kind: 'interface',
            declaration: printed,
            documentation,
            tags
          });
          recorded = true;
          break;
        }
      }

      if (recorded) {
        continue;
      }

      const declaration = declarations[0];
      const type = checker.getTypeOfSymbolAtLocation(symbol, declaration);
      const signatures = checker.getSignaturesOfType(type, ts.SignatureKind.Call);
      if (signatures.length === 0) {
        continue;
      }

      const signatureTexts = signatures.map((signature) => {
        return `function ${symbol.getName()}${checker.signatureToString(signature)}`;
      });

      exportDocs.push({
        name: symbol.getName(),
        kind: 'function',
        signature: signatureTexts.join('\n'),
        documentation,
        tags
      });
    }

    if (exportDocs.length > 0) {
      exportDocs.sort((a, b) => a.name.localeCompare(b.name));
      docs.push({
        filePath: fileName,
        exports: exportDocs
      });
    }
  }

  docs.sort((a, b) => a.filePath.localeCompare(b.filePath));
  return docs;
}

function renderDocs(root: string, files: FileDoc[]): string {
  const header: string[] = [];
  header.push('# API Reference');
  header.push('');
  header.push(`_Last generated: ${new Date().toISOString()}_`);
  header.push('');
  header.push('> ⚠️ This file is auto-generated by `npm run docs:api`. Do not edit by hand.');
  header.push('');

  const body: string[] = [...header];

  for (const file of files) {
    const relativePath = path.relative(root, file.filePath).split(path.sep).join('/');
    body.push(`## ${relativePath}`);
    body.push('');

    for (const entry of file.exports) {
      body.push(`### \`${entry.name}\``);
      body.push('');
      body.push(`*Kind*: ${entry.kind}`);
      if (entry.documentation) {
        body.push('');
        body.push(entry.documentation);
      }
      if (entry.tags && entry.tags.length > 0) {
        body.push('');
        for (const tag of entry.tags) {
          body.push(`- ${tag}`);
        }
      }
      body.push('');
      if (entry.kind === 'interface' && entry.declaration) {
        body.push('```ts');
        body.push(entry.declaration);
        body.push('```');
      } else if (entry.signature) {
        body.push('```ts');
        body.push(entry.signature);
        body.push('```');
      }
      body.push('');
    }
  }

  return body.join('\n');
}

async function main(): Promise<void> {
  const root = path.resolve(__dirname, '..');
  const program = loadProgram(root);
  const files = collectExportDocs(program);
  const outputPath = path.join(root, 'docs', 'API_REFERENCE.md');
  await ensureDirectory(outputPath);
  const content = renderDocs(root, files);
  await fs.writeFile(outputPath, content, 'utf8');
}

main().catch((error) => {
  console.error(error instanceof Error ? error.stack ?? error.message : error);
  process.exit(1);
});
